services:
  db:
    image: mariadb:10
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /opt/www/mysql:/var/lib/mysql
    networks:
      - wp_net

  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://%{SERVER_IP}%');
        define('WP_SITEURL','http://%{SERVER_IP}%');
    volumes:
      - /opt/www/wordpress:/var/www/html
    networks:
      - wp_net

  wpcli:
    image: wordpress:cli
    container_name: wp_cli
    depends_on:
      - wordpress
      - db
    volumes:
      - /opt/www/wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - wp_net

networks:
  wp_net:
    name: wordpress-network
